//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Services1 = new HashSet<Services>();
        }
    
        public int ID { get; set; }
        public string OrderCode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.TimeSpan OrderTime { get; set; }
        public int ClientCode { get; set; }
        public string Services { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> RentalTime { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual OrderStatuses OrderStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services> Services1 { get; set; }
    }
}
